dist: trusty
services:
  - docker

stages:
  - build
  - tests

notifications:
  email:
    recipients:
      - alexandre.flion@epitech.eu
      - huntearsgaming@gmail.com
    on_success: never
    on_failure: always

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

jobs:
  include:
    - stages: build
      name: "Build"
      if: type != cron
      install:
        - docker pull nheuillet/docker-epitech-c
      script:
        - docker run -v $PWD:/build nheuillet/docker-epitech-c bash -c "cd build && mkdir build && cd build && cmake .. && make"
    - stages: tests
      name: "Tests"
      if: type != cron
      install:
        - docker pull nheuillet/docker-epitech-c
      script:
        - docker run -v $PWD:/build nheuillet/docker-epitech-c bash -c "cd build && mkdir build && cd build && cmake .. && make && ./my_logger"
